[package]
name = "sebastian2852/actorutils"
version = "0.0.1"
description = "Promise-based messaging and utilities for Roblox's parallel Luau actors"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

license = "MIT"
authors = ["Sebastian2852"]

exclude = ["**"]
include = ["lib", "lib/**", "default.project.json", "LICENSE", "wally.toml"]

[dependencies]
Promise = "evaera/promise@4.0.0"